
services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: stock_analysis_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mongo
      - redis
      - kafka

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: stock_analysis_frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    container_name: stock_analysis_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:alpine
    container_name: stock_analysis_redis
    ports:
      - "6379:6379"

  zookeeper:
    image: bitnami/zookeeper:3.9
    container_name: stock_analysis_zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      
  kafka:
    image: bitnami/kafka:3.5
    container_name: stock_analysis_kafka
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
    depends_on:
      - zookeeper

volumes:
  mongo_data:
