
services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: stock_analysis_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mongo
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: stock_analysis_frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    container_name: stock_analysis_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:alpine
    container_name: stock_analysis_redis
    ports:
      - "6379:6379"

volumes:
  mongo_data:
